server:
  port: 8080
#文件上传路径

environments:
  dev:
    url: https://dev.example.com
    name: Developer Setup
  prod:
    url: https://another.example.com
    name: My Cool App



spring:
#  resources:
#    static-locations:
#
#  mvc:
#    static-path-pattern: /**

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/form_information_extraction?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
#      password: Nchu19980321lwt&lc
      password: 19980321lwt
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # db-type: com.alibaba.druid.pool.DruidDataSource

  servlet:  ##文件上传
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.nchu.entity







